blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index, name='home'),
    path('post/<int:id>/', views.post, name='post'),
    path('delete-comment/', views.delete_comment, name='delete-comment'),
    path('about/', views.about, name='about'),
    path('base/', views.base, name='base'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("account/", include("account.urls", namespace='account')),
    path("", include("contact.urls", namespace='contact')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from services.mixin import DateMixin, SlugMixin
from services.uploader import Uploader
from services.choices import STATUS
from services.generator import CodeGenerator
from services.slugify import slugify
from django.contrib.auth import get_user_model
from mptt.models import MPTTModel, TreeForeignKey
from django.db.models import Q
from ckeditor.fields import RichTextField

user = get_user_model()

class Category(DateMixin, MPTTModel):
    name = models.CharField(max_length=300)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    @property
    def blog_count(self):
        return Blog.objects.filter(Q(category_id=self.id) | Q(category__parent_id=self.id)).count()


class Tag(DateMixin):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Blog(DateMixin, SlugMixin):
    user_admin = models.ForeignKey(user, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=300)
    subject = models.TextField()
    text = RichTextField(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    view_count = models.PositiveIntegerField(null=True)
    status = models.CharField(max_length=100, choices=STATUS, default='Active')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

    def save(self, *args, **kwargs):
        self.code = CodeGenerator.create_activation_link_code(size=20, model_=Blog)
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    @property
    def popular_blogs(self):
        return Blog.objects.filter(Q(status='Active')).order_by('-view_count')[:3]

class BlogImage(DateMixin):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to=Uploader.upload_image_blog, max_length=500)

    def __str__(self):
        return self.blog.title

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'BlogImage'
        verbose_name_plural = 'BlogImages'


class Comment(DateMixin, MPTTModel):
    user = models.ForeignKey(user, on_delete=models.CASCADE, null=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, related_name='children')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
    message = models.TextField()

    def __str__(self):
        return f'{self.user.username} --- {self.parent}'

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    @property
    def comment_count(self):
        return Comment.objects.filter(blog_id=self.blog.id).count()

contact/models.py
from django.db import models
from services.mixin import DateMixin

class Contact(DateMixin):
    name = models.CharField(max_length=300)
    email = models.CharField(max_length=320)
    subject = models.CharField(max_length=400)
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    name = forms.CharField(min_length=2, max_length=300, label="Your name")
    email = forms.EmailField(min_length=3, max_length=320, label="Email address")
    subject = forms.CharField(min_length=3, max_length=600, label="Subject")
    message = forms.CharField(min_length=5, max_length=2000, label="Your message", widget=forms.Textarea())

    class Meta:
        model = Contact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                "class": "form-control"
            })

    def clean(self):
        name = self.cleaned_data.get('name')

        if name:
            if not name.replace(" ", "").replace(",", "").replace(".", "").isalpha():
                self.add_error("name", "Adınızı doğru daxil edin")

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from urllib.parse import urlparse
from .models import Blog, BlogImage, Category, Comment
from django.db.models import Q
from django.core.paginator import Paginator
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

user = get_user_model()


def index(request):
    blogs = Blog.objects.filter(status='Active')
    head_blogs = Blog.objects.filter(status='Active')[:8]

    filter_, filter_dict = Q(), {}

    category = request.GET.getlist("category", None)

    if category != "" and category:
        filter_dict["category"] = "".join(f'category={cat}&' for cat in category)
        filter_.add(Q(category__in=category), Q.AND)


    tag = request.GET.getlist("tag", None)

    if tag != "" and tag:
        filter_dict["tag"] = "".join(f'tag={cat}&' for cat in tag)
        filter_.add(Q(tags__in=tag), Q.AND)


    if request.method == "POST" and 'search' in request.POST:
        search = request.POST.get('search')
        filter_dict["search"] = search
        filter_.add(Q(title__icontains=search), Q.AND)

    blogs = blogs.filter(filter_)

    paginator = Paginator(blogs, 6)
    page = request.GET.get('page', 1)
    blog_list = paginator.get_page(page)

    context = {
        'blogs': blog_list,
        'head_blogs': head_blogs,
        "categories": Category.objects.filter(parent__isnull=True),
        'paginator': paginator,
        "filter_dict": filter_dict.values()
    }

    return render(request, 'blog/index.html', context)


def post(request, id):
    get_blog = get_object_or_404(Blog, id=id)

    get_blog.view_count += 1
    get_blog.save()

    comments = Comment.objects.filter(Q(parent__isnull=True)&(Q(blog=get_blog.id))).order_by('-created_at')

    get_user = None

    if request.user.username:
        get_user = user.objects.get(username=request.user.username) if user.objects.filter(
            username=request.user).exists() else None

    count_comment = get_blog.comment_set.filter(Q(user=get_user)&Q(parent__isnull=True)).count()
    count_reply_comment = get_blog.comment_set.filter(Q(user=get_user)&Q(parent__isnull=False)).count()

    if request.method == "POST" and "comment" in request.POST:
        comment = request.POST.get("comment")

        if count_comment < 3:
            Comment.objects.create(
                user=get_user,
                blog=get_blog,
                message=comment
            )

            return redirect('blog:post', get_blog.id)

    elif request.method == "POST" and "reply-comment" in request.POST:
        reply_comment = request.POST.get("reply-comment")
        parent_comment = Comment.objects.get(id=request.POST.get('reply-comment-id'))

        if count_reply_comment < 3:
            Comment.objects.create(
                user=get_user,
                parent=parent_comment,
                blog=get_blog,
                message=reply_comment
            )

            return redirect('blog:post', get_blog.id)

    context = {
        'blog': get_blog,
        "categories": Category.objects.filter(parent__isnull=True),
        'comments': comments
    }

    return render(request, 'blog/blog-single.html', context)

@login_required(login_url="/user/login/")
def delete_comment(request):
    data = {}
    get_object_or_404(user, username=request.user)

    comment = get_object_or_404(Comment, id=int(request.POST.get("commentID")))

    get_user = user.objects.get(username=request.user)

    if comment.user == get_user:
        comment.delete()
        data["success"] = True
    else:
        data["success"] = False

    return JsonResponse(data)


def about(request):
    context = {}
    return render(request, 'blog/about.html', context)


def base(request):
    url = request.POST.get('url')
    parsed_url = urlparse(url)
    path = parsed_url.path.strip('/')

    get_user = False

    if request.user.username:
        get_user = True if user.objects.filter(
            username=request.user).exists() else False

    data = {
        'user': get_user,
        'path': 'home' if path == "" else path
    }

    return JsonResponse(data)

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.conf import settings
from django.core.mail import send_mail


def contact(request):
    contactForm = ContactForm()

    if request.method == "POST":
        contactForm = ContactForm(request.POST or None)

        if contactForm.is_valid():
            contactForm.save()

            subject = contactForm.cleaned_data.get('subject')
            message = contactForm.cleaned_data.get('message')

            # sending mail

            send_mail(
                subject,  # subject
                message,  # message
                'settings.EMAIL_HOST_USER',  # from mail
                ['youremail@gmail.com', ],  # to mail
                fail_silently=False,
            )

            return redirect("contact:contact")

    context = {
        "contact": contactForm
    }

    return render(request, 'blog/contact.html', context)

templates/blog/about.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

    <!-- page header -->
    <section class="page-header">
        <div class="container-xl">
            <div class="text-center">
                <h1 class="mt-0 mb-2">About</h1>
            </div>
        </div>
    </section>

	<!-- section main content -->
	<section class="main-content">
		<div class="container-xl">

			<div class="row gy-4">

				<div class="col-lg-8">

                    <div class="page-content bordered rounded padding-30">

                        <img src="{% static 'assets/images/other/about.jpg' %}" alt="Morgan George" class="rounded mb-4" />

                        <p>Hello, We are content writers about technology, science and general lifestyle. We share a new blog for you every day.</p>
                        <p>Morgan Blog was established on March 26, 2023 to deliver new information to internet users, to make them more understandable and entertaining. You can access scientific articles, technology topics and more information on our website.</p>
                        <p> With thousands of visitors per month, our Morgan Blog Website will continue to bring new information to people.</p>

                        <hr class="my-4" />
                        <ul class="social-icons list-unstyled list-inline mb-0">
                            <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
                        </ul>
                        
                    </div>

                </div>
				<div class="col-lg-4">

					<!-- sidebar -->
					<div class="sidebar">
						<!-- widget about -->
						<div class="widget rounded">
							<div class="widget-about data-bg-image text-center" data-bg-image="{% static 'assets/images/map-bg.png' %}">
								<img width="80" src="{% static 'assets/images/logo.png' %}" alt="logo" class="mb-4" />
								<p class="mb-4">Hello, We are content writers about technology, science and general lifestyle. We share a new blog for you every day.</p>
								<ul class="social-icons list-unstyled list-inline mb-0">
									<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
								</ul>
							</div>
						</div>

						</div>

					</div>

				</div>
			</div>

	</section>

{% endblock %}

templates/blog/blog-single.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

<style>
.image-container-popular-blog {
  width: 50px;
  height: 50px;
  margin-left: 9px;
  border-radius: 50%;
  overflow: hidden;
}

.image-container-popular-blog img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.image-container-comment-photo {
  width: 50px;
  height: 50px;
  margin-left: 15px;
  border-radius: 50%;
  overflow: hidden;
}

.image-container-comment-photo img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

</style>

	<!-- section main content -->
	<section class="main-content mt-3">
		<div class="container-xl">

			<div class="row gy-4">

				<div class="col-lg-8">
					<!-- post single -->
                    <div class="post post-single">
						<!-- post header -->
						<div class="post-header">
							<h1 class="title mt-0 mb-3">{{ blog.title }}</h1>
							<ul class="meta list-inline mb-0">
								<li class="list-inline-item">{{ blog.user_admin }}</li>
								<li class="list-inline-item">{{ blog.category }}</li>
								<li class="list-inline-item">{{ blog.created_at }}</li>
							</ul>
						</div>
						<!-- featured image -->
						<div class="featured-image">
							<img src="{{ blog.blogimage_set.first.image.url }}" alt="post-title" />
						</div>
						<!-- post content -->
						<div class="post-content clearfix">
							<h4>{{blog.subject|safe}}</h4>

							<p> {{blog.text|safe}} </p>
							
							</div>
						<!-- post bottom section -->
						<div class="post-bottom">
							<div class="row d-flex align-items-center">
								<div class="col-md-6 col-12 text-center text-md-start">
									<!-- tags -->
									{% for tag in blog.tags.all %}
										<a href="/?tag={{tag.id}}" class="tag">#{{tag}}</a>
									{% endfor %}
								</div>
								<div class="col-md-6 col-12">
									<!-- social icons -->
									<ul class="social-icons list-unstyled list-inline mb-0 float-md-end">
										<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fab fa-telegram-plane"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="far fa-envelope"></i></a></li>
									</ul>
								</div>
							</div>
						</div>

                    </div>

					<div class="spacer" data-height="50"></div>

					<!-- section header -->
					<div class="section-header">
						<h3 class="section-title">Comments ({% if blog.comment_set.first.comment_count %} {{ blog.comment_set.first.comment_count }} {% else %}0{% endif %})</h3>
						<img src="{% static 'assets/images/wave.svg' %}" class="wave" alt="wave" />
					</div>
					<!-- post comments -->
					<div class="comments bordered padding-30 rounded">

						<ul class="comments">
							<!-- comment item -->

							{% for comment in comments %}

								<li id="comment-container-{{comment.id}}" class="comment rounded">

									{% if comment.user == request.user %}

									<div style="float: right">
										<div class="dropdown">
										  <button class="btn " type="button" id="dropdownMenuButton-{{comment.id}}" data-bs-toggle="dropdown" aria-expanded="false">
											<i style="color: gray" class="bi bi-three-dots-vertical"></i>
										  </button>
										  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton-{{comment.id}}">
											<li><a class="dropdown-item" onclick="deleteComment({{comment.id}})">Delete comment</a></li>
										  </ul>
										</div>
									</div>

									{% endif %}

									<div class="thumb image-container-comment-photo">
										{% if comment.user.profile_photo %}
											<img src="{{ comment.user.profile_photo.url }}" alt="John Doe" />
										{% endif %}
									</div>
									<div class="details">
										<h4 class="name"><a href="#">{{ comment.user.username }}</a></h4>
										<span class="date">{{ comment.created_at }}</span>
										<p>{{ comment.message }}</p>
										{% if comment.children.all|length %}
											<button type="button" style="background: #ed7a6b" id="replies-comment-{{comment.id}}" onclick="replies({{comment.id}})" class="btn btn-default btn-sm"><i class="bi bi-arrow-down"></i> {{ comment.children.all|length }} Replies </button>
										{% endif %}
										{% if request.user.is_authenticated %}
											<button type="button" id="reply-comment-{{comment.id}}" onclick="reply({{comment.id}});" class="btn btn-default btn-sm">Reply</button>
										{% endif %}
										<div style="display: none;" id="reply-container-{{comment.id}}">
											<hr>

											<form method="post">
												{% csrf_token %}

												<div class="row">
													<div class="column col-md-12">
														<!-- Comment textarea -->
														<div class="form-group">
															<input type="hidden" name="reply-comment-id" value="{{ comment.id }}">
															<textarea name="reply-comment" class="form-control" rows="4" placeholder="Your reply comment here..." required="required"></textarea>
														</div>
													</div>
												</div>

												<button type="button" id="cancel-reply" onclick="cancelReply({{comment.id}})" name="reply-comment" class="btn btn-danger btn-sm">Cancel</button>
												<button type="submit" class="btn btn-default btn-sm">Submit</button>

											</form>

										</div>
									</div>

								</li>

							<!-- comment reply -->

							<div id="replies-{{comment.id}}" style="display: none">

								{% for reply_comment in comment.children.all %}

									<!-- comment item -->
									<li id="comment-container-{{reply_comment.id}}" class="comment child rounded">

										{% if reply_comment.user == request.user %}

										<div style="float: right">
											<div class="dropdown">
											  <button class="btn" type="button" id="dropdownMenuButton-{{reply_comment.id}}" data-bs-toggle="dropdown" aria-expanded="false">
												<i style="color: gray" class="bi bi-three-dots-vertical"></i>
											  </button>
											  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton-{{reply_comment.id}}">
												<li><a class="dropdown-item" onclick="deleteComment({{reply_comment.id}})">Delete comment</a></li>
											  </ul>
											</div>
										</div>

										{% endif %}

										<div class="thumb image-container-comment-photo">
											{% if reply_comment.user.profile_photo %}
												<img src="{{ reply_comment.user.profile_photo.url }}" alt="John Doe" />
											{% endif %}
										</div>
										<div class="details">
											<h4 class="name"><a href="#">{{ reply_comment.user.username }}</a></h4>
											<span class="date">{{ reply_comment.created_at }}</span>
											<p>{{ reply_comment.message }}</p>

										</div>
									</li>

								{% endfor %}

								</div>

							{% endfor %}

						</ul>
					</div>

					<div class="spacer" data-height="50"></div>

					{% if request.user.is_authenticated %}

					<!-- section header -->
					<div class="section-header">
						<h3 class="section-title">Leave Comment</h3>
						<img src="{% static 'assets/images/wave.svg' %}" class="wave" alt="wave" />
					</div>
					<!-- comment form -->
					<div class="comment-form rounded bordered padding-30">

						<form id="comment-form" class="comment-form" method="post">
							{% csrf_token %}
				
							<div class="messages"></div>
							
							<div class="row">

								<div class="column col-md-12">
									<!-- Comment textarea -->
									<div class="form-group">
										<textarea name="comment" class="form-control" rows="4" placeholder="Your comment here..." required="required"></textarea>
									</div>
								</div>
						
							</div>
	
							<button type="submit" name="submit" id="submit" value="Submit" class="btn btn-default">Submit</button>
	
						</form>
					</div>

					{% endif %}

                </div>

				<div class="col-lg-4">

					<!-- sidebar -->
					<div class="sidebar">
						<!-- widget about -->
						<div class="widget rounded">
							<div class="widget-about data-bg-image text-center" data-bg-image="{% static 'assets/images/map-bg.png' %}">
								<img width="80" src="{% static 'assets/images/logo.png' %}" alt="logo" class="mb-4" />
								<p class="mb-4">Hello, We’re content writer who is fascinated by content fashion, celebrity and lifestyle. We helps clients bring the right content to the right people.</p>
								<ul class="social-icons list-unstyled list-inline mb-0">
									<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
								</ul>
							</div>
						</div>

						<!-- widget popular posts -->
						<div class="widget rounded">
							<div class="widget-header text-center">
								<h3 class="widget-title">Popular Posts</h3>
								<img src="{% static 'assets/images/wave.svg' %}" class="wave" alt="wave" />
							</div>
							<div class="widget-content">
								<!-- post -->

								{% for popular_blog in blog.popular_blogs %}

									<div class="post post-list-sm circle">
										<div class="thumb circle">
											<a href="{% url 'blog:post' popular_blog.id %}">
												<div class="image-container-popular-blog ">
													<img src="{{ popular_blog.blogimage_set.first.image.url }}" alt="post-title" />
												</div>
											</a>
										</div>
										<div class="details clearfix">
											<h6 class="post-title my-0"><a href="{% url 'blog:post' popular_blog.id %}">{{ popular_blog.title }}</a></h6>
											<ul class="meta list-inline mt-1 mb-0">
												<li class="list-inline-item">{{ popular_blog.created_at|date:"d M, Y" }}</li>
											</ul>
										</div>
									</div>

								{% endfor %}

							</div>
						</div>

						<!-- widget categories -->
						<div class="widget rounded">
							<div class="widget-header text-center">
								<h3 class="widget-title">Explore Topics</h3>
								<img src="{% static 'assets/images/wave.svg' %}" class="wave" alt="wave" />
							</div>
							<div class="widget-content">
								<ul class="list">
									{% for category in categories %}
										{% if category.blog_count != 0 %}

											<li><a href="/?category={{ category.id }}">{{ category.name }}</a><span>({{category.blog_count}})</span></li>

										{% endif %}
									{% endfor %}
								</ul>
							</div>
							
						</div>

					</div>

				</div>

			</div>

		</div>
	</section>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>

	function reply(id) {
		$('#reply-container-' + id).show();
		$('#reply-comment-' + id).hide();
	};

	function cancelReply(id) {
		$('#reply-container-' + id).hide();
		$('#reply-comment-' + id).show();
	};

	function replies(id) {
		var icon = $('#replies-comment-' + id).find('i');
      	icon.toggleClass('bi-arrow-down bi-arrow-up');

      	$('#replies-' + id).slideToggle("fast");
	};

	function deleteComment(id) {
		const deleteCommentUrl = "{% url 'blog:delete-comment' %}"

		$.ajax({
			type: "POST",
			url: deleteCommentUrl,
			data: {
				csrfmiddlewaretoken: '{{ csrf_token }}',
				action: 'post',
				commentID: id,
			},

			success: function (data){
				if (data.success) {
					location.reload()
				}
			},

			error: function (xhr, errmsg, err) {},

		});
	}
</script>


{% endblock %}