account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),

    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(
         template_name="account/password_reset_form.html",
         success_url='password_reset_email_confirm',
         email_template_name='account/password_reset_email.html',
         form_class=PwdResetForm), name='pwdreset'),

    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
         template_name='account/password_reset_confirm.html',
         success_url='/account/password_reset_complete/',
         form_class=PwdResetConfirmForm), name="password_reset_confirm"),

    path('password_reset/password_reset_email_confirm/', TemplateView.as_view(template_name="account/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/', TemplateView.as_view(template_name="account/reset_status.html"), name='password_reset_complete'),

    # User dashboard
    path('edit/', views.edit_details, name='edit_details'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('delete_confirm/', TemplateView.as_view(template_name="account/delete_confirm.html"), name='delete_confirmation'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index, name='home'),
    path('post/<int:id>/', views.post, name='post'),
    path('delete-comment/', views.delete_comment, name='delete-comment'),
    path('about/', views.about, name='about'),
    path('base/', views.base, name='base'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("account/", include("account.urls", namespace='account')),
    path("", include("contact.urls", namespace='contact')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/account-base.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <link href="{% static 'assets/vendor/fontawesome/css/fontawesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/solid.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/brands.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/master.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/flagiconcss/css/flag-icon.min.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <!-- sidebar navigation component -->
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="/"><img src="{% static 'assets/images/main-logo.png' %}" width="50" alt="bootraper logo" class="app-logo"></a>
            </div>
            <ul class="list-unstyled components text-secondary">
                <li>
                    <a href="{% url 'account:edit_details' %}"><i class="fas fa-file-alt"></i>Edit Details</a>
                </li>
            </ul>
        </nav>
        <div id="body" class="active">
            <!-- navbar navigation component -->
            <nav class="navbar navbar-expand-lg navbar-white bg-white">
                <button type="button" id="sidebarCollapse" class="btn btn-light">
                    <i class="fas fa-bars"></i><span></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ms-auto">
                        <li class="nav-item dropdown">
                            <div class="nav-dropdown">
                                <a href="#" id="nav1" class="nav-item nav-link dropdown-toggle text-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-link"></i> <span>Short Links</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end nav-link-menu" aria-labelledby="nav1">
                                    <ul class="nav-list">
                                        <li><a href="/" class="dropdown-item"><i class="fas fa-home"></i> Home Page </a></li>
                                        <div class="dropdown-divider"></div>
                                        <li><a href="/shop/" class="dropdown-item"><i class="fas fa-book"></i> Blogs </a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <div class="nav-dropdown">
                                <a href="#" id="nav2" class="nav-item nav-link dropdown-toggle text-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-user"></i> <span id="account">{{request.user}}</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end nav-link-menu">
                                    <ul class="nav-list">
                                        <li><a id="logout" href="{% url 'account:logout' %}" class="dropdown-item"><i class="fas fa-sign-out-alt"></i> Çıxış Et </a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            {% block body %}
            {% endblock %}

        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>
</body>

</html>

templates/base.html
{% load static %}

<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Morgan - Blog</title>
	<meta name="description" content="Morgan - Blog">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}">

	<!-- STYLES -->
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'assets/css/slick.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'assets/css/simple-line-icons.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- preloader -->
<div id="preloader">
	<div class="book">
		<div class="inner">
			<div class="left"></div>
			<div class="middle"></div>
			<div class="right"></div>
		</div>
		<ul>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
</div>

<!-- site wrapper -->
<div class="site-wrapper">

	<div class="main-overlay"></div>

	<!-- header -->
	<header class="header-default">
		<nav class="navbar navbar-expand-lg">
			<div class="container-xl">
				{% csrf_token %}
				<!-- site logo -->
				<a class="navbar-brand" href="/"><img width="65" src="{% static 'assets/images/logo.png' %}" alt="logo" /></a>

				<div class="collapse navbar-collapse">
					<!-- menus -->
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="/">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/about/">About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/contact/">Contact</a>
						</li>
					</ul>
				</div>

				<!-- header right section -->
				<div class="header-right">
					<!-- header buttons -->
					<div class="header-buttons">
						<a id="account-link" href="/account/login">
							<button id="account-btn" style="background: linear-gradient(to right, #FE4F70 0%, #FFA387 100%); padding: 9px 25px" class="btn">
								<i class="bi bi-person"></i> Login
							</button>
						</a>
						<button class="search icon-button">
							<i class="icon-magnifier"></i>
						</button>
						<button class="burger-menu icon-button">
							<span class="burger-icon"></span>
						</button>
					</div>
				</div>
			</div>
		</nav>
	</header>

    {% block body %}
    {% endblock %}


	<!-- footer -->
	<footer>
		<div class="container-xl">
			<div class="footer-inner">
				<div class="row d-flex align-items-center gy-4">
					<!-- copyright text -->
					<div class="col-md-4">
						<span class="copyright"> © 2021 Morgan George Blog Website</span>
					</div>

					<!-- social icons -->
					<div class="col-md-4 text-center">
						<ul class="social-icons list-unstyled list-inline mb-0">
							<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
						</ul>
					</div>

					<!-- go to top button -->
					<div class="col-md-4">
						<a href="#" id="return-to-top" class="float-md-end"><i class="icon-arrow-up"></i>Back to Top</a>
					</div>
				</div>
			</div>
		</div>
	</footer>

</div><!-- end site wrapper -->

<!-- search popup area -->
<div class="search-popup">
	<!-- close button -->
	<button type="button" class="btn-close" aria-label="Close"></button>
	<!-- content -->
	<div class="search-content">
		<div class="text-center">
			<h3 class="mb-4 mt-0">Press ESC to close</h3>
		</div>
		<!-- form -->
		<form class="d-flex search-form" action="/" method="post">
			{% csrf_token %}
			<input class="form-control me-2" type="search" name="search" placeholder="Search and press enter ..." aria-label="Search">
			<button class="btn btn-default btn-lg" type="submit"><i class="icon-magnifier"></i></button>
		</form>
	</div>
</div>

<!-- canvas menu -->
<div class="canvas-menu d-flex align-items-end flex-column">
	<!-- close button -->
	<button type="button" class="btn-close" aria-label="Close"></button>

	<!-- logo -->
	<div class="logo">
		<img width="80" src="{% static 'assets/images/logo.png' %}" alt="Morgan" />
	</div>

	<!-- menu -->
	<nav>
		<ul class="vertical-menu">
			<li><a href="/">Home</a></li>
			<li><a href="/about/">About</a></li>
			<li><a href="/contact/">Contact</a></li>
		</ul>
	</nav>

	<!-- social icons -->
	<ul class="social-icons list-unstyled list-inline mb-0 mt-auto w-100">
		<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
	</ul>
</div>

<!-- JAVA SCRIPTS -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>-->

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<!--<script src="{% static 'assets/js/popper.min.js' %}"></script>-->
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.sticky-sidebar.min.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>

<script>

$.ajax({
  type: "POST",
  url: '{% url 'blog:base' %}',
  data: {
    csrfmiddlewaretoken: '{{ csrf_token }}',
    url: window.location.href,
    action: "post",
  },
  success: function (response) {

    $('.nav-link').filter(function() {
	  return $(this).text().toLowerCase() === response.path;
	}).parent().addClass('active');

	$('.vertical-menu li a').filter(function() {
	  return $(this).text().toLowerCase() === response.path;
	}).parent().addClass('active');

	if (response.user){
		$('#account-link').attr('href', '/account/dashboard/');
		$('#account-btn').html('<i class="bi bi-person"></i> Account');
	}

  },
  error: function (xhr, errmsg, err) {},
});

</script>

</body>
</html>